{{- if eq .Values.mode "deployment" }}
{{- if not .Values.configMap.existingName }}
{{- fail "configMap.existingName is required" }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-collector
  labels:
    app.kubernetes.io/name: collector
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: collector
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    {{- include "collector.podTemplate" . | nindent 4 }}
{{- end }}
