{{- if or .Values.secret.otlpEndpoint .Values.secret.licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-collector-secret
  labels:
    app.kubernetes.io/name: collector
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{- if .Values.secret.otlpEndpoint }}
  otlp-endpoint: {{ .Values.secret.otlpEndpoint | quote }}
  {{- end }}
  {{- if .Values.secret.licenseKey }}
  license-key: {{ .Values.secret.licenseKey | quote }}
  {{- end }}
{{- end }}
